package com.useraddress.user_address.util.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

@Getter
@AllArgsConstructor
@NoArgsConstructor
public enum ErrorCode {

    // DATA ERRORS 800 - 829 //
    EMAIL_NOT_CORRECT(801, "EMAIL_NOT_CORRECT"),
    PHONE_NUMBER_NOT_CORRECT(802, "PHONE_NUMBER_NOT_CORRECT"),
    DATA_TYPE_MISMATCH(803, "DATA_TYPE_MISMATCH"),
    INCOMPLETE_DATA(817, "INCOMPLETE_DATA"),
    OBJECT_CAN_NOT_BE_UPDATED(818, "OBJECT_CAN_NOT_BE_UPDATED"),
    NAME_CAN_NOT_BE_NULL(825, "NAME_CAN_NOT_BE_NULL"),
    LAST_NAME_CAN_NOT_BE_NULL(826, "LAST_NAME_CAN_NOT_BE_NULL"),
    SECOND_LAST_NAME_CAN_NOT_BE_NULL(827, "SECOND_LAST_NAME_CAN_NOT_BE_NULL"),
    EMAIL_CAN_NOT_BE_NULL(828, "EMAIL_CAN_NOT_BE_NULL"),
    PHONE_NUMBER_CAN_NOT_BE_NULL(829, "PHONE_NUMBER_CAN_NOT_BE_NULL"),

    // ARGUMENTS ERRORS 830 - 839 //
    MISSING_ARGUMENTS_IN_BODY(830, "MISSING_ARGUMENTS_IN_BODY"),
    OBJECT_NOT_EXISTS(831, "OBJECT_NOT_EXISTS"),
    OBJECT_ALREADY_EXISTS(832, "OBJECT_ALREADY_EXISTS"),
    OBJECT_WITHOUT_CHANGES(833, "OBJECT_WITHOUT_CHANGES"),
    INVALID_REMOVE(835, "INVALID_REMOVE"),
    NOT_ACCEPTABLE(837, "NOT_ACCEPTABLE"),
    OBJECT_MUST_NOT_BE_NULL(838, "OBJECT_MUST_NOT_BE_NULL"),

    // LIST ERRORS 880 - 889 //
    LIST_IS_NULL(880, "LIST_IS_NULL"),

    // USER ERRORS 1020 - 1029 //
    USER_EMAIL_ALREADY_EXISTS(1020, "USER_EMAIL_ALREADY_EXISTS"),
    USER_PHONE_NUMBER_ALREADY_EXISTS(1021, "USER_PHONE_NUMBER_ALREADY_EXISTS"),
    USER_CURP_ALREADY_EXISTS(1027, "USER_CURP_ALREADY_EXISTS"),
    USER_RFC_ALREADY_EXISTS(1028, "USER_RFC_ALREADY_EXISTS"),
    USER_ID_CAN_NOT_BE_NULL(1029, "USER_ID_CAN_NOT_BE_NULL"),

    // GENERAL ERRORS 2110 - 2120 //
    GENERATE_REPORT_FAILED(2111, "GENERATE_REPORT_FAILED"),
    UNKNOWN_ERROR(2116, "UNKNOWN_ERROR"),

    // JDBC ERRORS 2211 - 2220 //
    DB_CONNECTION_UNAVAILABLE(2212, "DB_CONNECTION_UNAVAILABLE"),
    JDBC_DUPLICATE_KEY(2215, "JDBC_DUPLICATE_KEY"),
    JDBC_UNEXPECTED_EXCEPTION(2216, "JDBC_UNEXPECTED_EXCEPTION"),

    // USER MODULE ERRORS 3100 - 3119 //
    USER_NOT_EXISTS(3100, "USER_NOT_EXISTS"),
    USER_CURP_NOT_CORRECT(3101, "USER_CURP_NOT_CORRECT"),
    USER_RFC_NOT_CORRECT(3102, "USER_RFC_NOT_CORRECT"),
    USER_CAN_NOT_BE_DELETED(3103, "USER_CAN_NOT_BE_DELETED"),
    USER_SEARCH_CRITERIA_NOT_VALID(3104, "USER_SEARCH_CRITERIA_NOT_VALID"),

    // ADDRESS MODULE ERRORS 3120 - 3139 //
    ADDRESS_NOT_EXISTS(3120, "ADDRESS_NOT_EXISTS"),
    ADDRESS_DOES_NOT_BELONG_TO_USER(3121, "ADDRESS_DOES_NOT_BELONG_TO_USER"),
    ADDRESS_POSTAL_CODE_NOT_CORRECT(3122, "ADDRESS_POSTAL_CODE_NOT_CORRECT"),
    ADDRESS_ALREADY_EXISTS(3123, "ADDRESS_ALREADY_EXISTS"),
    ADDRESS_USER_ID_CAN_NOT_BE_NULL(3124, "ADDRESS_USER_ID_CAN_NOT_BE_NULL"),
    ADDRESS_CAN_NOT_BE_DELETED(3125, "ADDRESS_CAN_NOT_BE_DELETED");

    private int value;
    private String label;
}
