package com.useraddress.user_address.address.dto;

import java.time.LocalDateTime;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "Address stored in the system.")
public record AddressResponse(

        @Schema(description = "Identifier generated by the system")
        String id,

        @Schema(description = "Identifier of the user that owns the address")
        String userId,

        @Schema(description = "Street", example = "Av. Insurgentes Sur")
        String street,

        @Schema(description = "Exterior number", example = "1234")
        String exteriorNumber,

        @Schema(description = "Interior number, null when the address has none", example = "5B")
        String interiorNumber,

        @Schema(description = "Neighborhood", example = "Del Valle")
        String neighborhood,

        @Schema(description = "Postal code", example = "03100")
        String postalCode,

        @Schema(description = "City", example = "Ciudad de Mexico")
        String city,

        @Schema(description = "State", example = "Ciudad de Mexico")
        String state,

        @Schema(description = "Country", example = "Mexico")
        String country,

        @Schema(description = "Moment the address was created")
        LocalDateTime createdAt,

        @Schema(description = "Moment of the last update")
        LocalDateTime updatedAt) {
}
