package com.useraddress.user_address.user.dto;

import java.time.LocalDateTime;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema(description = "User stored in the system.")
public record UserResponse(

        @Schema(description = "Identifier generated by the system")
        String id,

        @Schema(description = "First name", example = "Juan")
        String name,

        @Schema(description = "Father's last name", example = "Perez")
        String lastName,

        @Schema(description = "Mother's last name", example = "Lopez")
        String secondLastName,

        @Schema(description = "CURP", example = "PELJ900101HDFRPN09")
        String curp,

        @Schema(description = "RFC", example = "PELJ900101AB1")
        String rfc,

        @Schema(description = "Email", example = "juan.perez@example.com")
        String email,

        @Schema(description = "Phone number", example = "+52 55 1234 5678")
        String phoneNumber,

        @Schema(description = "Moment the user was created")
        LocalDateTime createdAt,

        @Schema(description = "Moment of the last update")
        LocalDateTime updatedAt) {
}
